# Generated by Django 6.0.2 on 2026-02-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Binary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binaryvarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
